### ISSUE TITLE
[Feature request] : Zero configuration

### ISSUE THREAD

**Issue by canonic-epicure** [nonara/ts-patch#12]
Shouldn't the `ts-patch` just auto-patch the local TS on installation? If user add `ts-patch` as dependency, s/he clearly has an intention to patch the TS? This should be doable with `npm` hooks?

In the same way it can unpatch the TS upon un-installation (if there's a corresponding hook).

This will make `ts-pacth` zero-configuration utility.

**Comment by nonara** [comment]
I've considered that approach. The problem is that `ts-patch` is often used in non-standard ways or with certain configuration. Some examples:

1) User installs ts-patch globally in order to use it to patch specific projects when desired
2) One project may only require only _certain libraries_ be patched (ie typescript.js, tsc.js). (Unfortunately, some transformers tend to break the IDE when integrated with `tsserverlibrary,js`)
3) Some projects may want to patch only a specific installation of typescript while leaving the primary one unpatched
4) Some use it programatically

That said, it's easy to configure your package to auto-install by using `prepare` or `install` scripts in package.json.

**Comment by canonic-epicure** [comment]
Ok, thanks for reply.
