### ISSUE TITLE
[Question] Any example of macros-like, source-modifying transformer?

### ISSUE THREAD

**Issue by canonic-epicure** [nonara/ts-patch#14]
Hello,

I'm trying to implement the following "macros-transformer". 

I'd like to expand a definition like:
```ts
class SourceClass {
    @lazy
    lazyProperty    : Map<number, string>       = new Map()
}
```
to:
```ts
class TransformedClass {
    $lazyProperty   : Map<number, string>       = undefined

    get lazyProperty () : Map<number, string> {
        if (this.$lazyProperty !== undefined) return this.$lazyProperty

        return this.$lazyProperty = new Map()
    }

    set lazyProperty (value : Map<number, string>) {
        this.$lazyProperty = value
    }
}
```
And I want to make the `$lazyProperty` to be available for the rest of the program (to be able to check the lazy value presence).

For that I need the transformation to happen before the type-checking stage in compiler's pipeline. Is there any example of similar transformer? Is this something that can be done with the `program` transformer?

**Comment by cevek** [comment]
for now ts compiler doesn’t allow pre transformation of the source code. it is heavily depends on source text. it is possible, but the way is very tricky - in fs reading stage you parse ts file, transform it, then compile again to ts source and then provide result text file to the compiler. but this way has caveats like you lose original positions and errors and sourcemaps will be broken. to avoid that you should to remap these lines manually by patching methods which work with positions

**Comment by nonara** [comment]
@cevek is correct! Losing the position information is generally too high of a cost to be worth the benefit.

What I would suggest for your purposes would be to make a helper function to check. Example would be `isLazyPropertyLoaded(TransformedClass, 'lazyProperty')`, which would check '$' + param2 on param1.

**Comment by canonic-epicure** [comment]
So, no examples of such transformer exists? Very surprising.

@cevek Why the AST -> string -> AST transformation cycle is needed? I might be missing something, but as suggested [here](https://stackoverflow.com/a/59147818/365104), one can override the `getSourceFile` method of the `CompilerHost` instance. This method seems to return the already parsed `SourceFile`. One can just replace the original definition Nodes with expanded?

The source file positions can be kept unchanged for the all Nodes except the newly expanded ones? For the new nodes, one can set the file position to originate at the source node and to have length of 0 may be (to not affect the positions of other code).

Perhaps I'm missing something, as I'm not experienced with transformers yet, but can't believe nobody has already made a "macros" transformer.

**Comment by canonic-epicure** [comment]
It seems for purposes of macros expansion the "program" transformer is hooked too late - onto the "emit" method. By that time, there are already `getGlobalDiagnostics` and `getSemanticDiagnostics` called.

How is the "program" transformer different from the "before" and "after"? I'd expect the "program" transformer to completely override the usual TS pipeline.. But I'm biased of course and looking from the macros use case perspective. Probably "program" transformer solves some other use case.

**Comment by nonara** [comment]
It would be technically possible to do by doing a regular transform and using `ts-patch` diagnostic altering functions to find and remove diagnostic errors regarding references to added properties. In that manner, youd have no position mismatch in sourcemaps.

That would cover tsc, however, you'd also have to write a language service plugin which did the same, as the errors in your IDE come from the LanguageService.

That sort of thing takes a strong knowledge of the TypeScript compiler. It can be done, but in most cases, a simpler solution is better.

**Comment by canonic-epicure** [comment]
> It would be technically possible to do by doing a regular transform and using ts-patch diagnostic altering functions to find and remove diagnostic errors regarding references to added properties.

@nonara That would work, however it would be just a workaround for this particular case. I'm aiming for a general solution that can introduce new symbols, including new types (want to implement transformer for mixins, may be for sum types etc).

> for now ts compiler doesn’t allow pre transformation of the source code. it is heavily depends on source text. it is possible, but the way is very tricky - in fs reading stage you parse ts file, transform it, then compile again to ts source and then provide result text file to the compiler. but this way has caveats like you lose original positions and errors and sourcemaps will be broken. to avoid that you should to remap these lines manually by patching methods which work with positions

@cevek Is there any example available? 

What if the new symbols will be all placed on the same line  - that way the positions of other symbols in the file won't change?

**Comment by nonara** [comment]
There is no native way to do it. Even with what cevek mentioned, the language service in the IDE will still report errors, because it's entirely separate from the TSC process.

What you're talking about goes beyond transformer capability and gets into the territory of extending the typescript compiler itself. This leaves you with the options of forking typescript or of creating a dual language-service + transformer scenario using either program transformer or source transformer. 

1. With the program transformer, you could avoid altering diagnostics in tsc, however, you'd need to find a way to manually update the generated sourcemaps. This would mean studying how they're built so you could make sure they matched the original source instead of your updated source. That would ensure debugging works smoothly.

2. With source transformer, your sourcemaps would be fine, as they'd be generated by tsc during the transform process. After that, you'd simply need to find and remove relevant diagnostic errors..

When you've accomplished either of those routes, you'll still need to remove diagnostics via a language service plugin, assuming that is still possible.

Believe it or not, while it feels hacky, that type of methdology is employed by Angular and others to add in their extensions without forking the compiler. If you think about it, TypeScript has two parts. 1) A compiler, 2) A Diagnostics reporter. Transformation can take care of the compiler side, and altering the results of the diagnostics report takes care of the other. This affords you the ability to alter TS behaviour without forking it.

Officially, TypeScript doesn't support changing/adding to diagnostics. Unofficially, it's built in a way that allows it to be done, which things like Angular rely on.

That said, if you prefer the behaviour to be a part of the TypeScript compiler, itself, you'd probably be better served forking.

I wish you luck! What you're hoping to do isn't easy, but it's not impossible. If you decide to pursue it, you will likely be spending a lot of time in the TS compiler base. At this level, you're not likely to find any tutorials or answers to questions along the way from StackOveflow, etc. It's even rare to get answers in the #compiler discord room, which is where the few people who work in the compiler tend to congregate. This is simply because there are very few people who know it well enough. So whatever you take on in extending compiler functionality will be mostly solo pioneering! Just a heads up if you decide to take it on.

Again - best of luck.

**Comment by canonic-epicure** [comment]
Thank you! It seems this task is more complex than I thought initially. However, as you mentioned, it seems that it is doable. It is very tempting to implement it - the possibilities looks endless. I'll be making attempts from time to time. Hopefully one day I'll submit a PR with support for `type : 'macros'` transformers :)
