### ISSUE TITLE
Intellisense in VS Code

### ISSUE THREAD

**Issue by trusktr** [nonara/ts-patch#15]
Is there a way we can have VS Code use ts-patch so we get intellisense for non standard syntax that we may implement with ts-patch?

I saw the section on modifying diagnostics, which I suppose gets us part of the way there. Now it would be a matter of how to get VS Code to run ts-patch instead of tsc, so that it can read the new diagnostics? What about intellisense features?

**Comment by nonara** [comment]
IDEs like VS Code use what is called a Language Service, which is a special instance of typescript. TS has native support for Language Service plugins, which can allow you to alter intellisense.

Look into writing a Language Service plugin. That should help! Good luck with it!

**Comment by freedomhero** [comment]
@nonara Is there a way to also implement a custom language service in a single ts-patch plugin? 


The Language Service Plugin uses an entry function like this:

```ts
function init(modules: { typescript: typeof import("typescript/lib/tsserverlibrary") }) {
 ...
}
export init;
```

While ts-patch plugin may look like:

```ts
export default function (
  program: ts.Program, 
  host: ts.CompilerHost | undefined, 
  options: PluginConfig, 
  { ts: tsInstance }: ProgramTransformerExtras
) { ... }

```

**Comment by nonara** [comment]
@freedomhero Hello. Yes. You can make your language server be exported using export = in the package index file, then add a second file with your transformer to the same package.

If the package was named `my-plugin`, and your language server plugin was in `index.js`, you would add a tsconfig plugin entry for the language server via `"plugin": "my-plugin"`

Then assuming you had your transformer in the file `transformer.js` you would add a transgorm plugin entry like `"transform": "my-plugin/transform"`

One entry for the LS and one for the transformer. Both cannot be in the same file due to language service plugins seemingly requiring you to use `export =`, but two files should work.

Hope that helps!

**Comment by freedomhero** [comment]
@nonara Thanks for the advice. It works for me.
