### ISSUE TITLE
Add ability to alter diagnostics in ts-node

### ISSUE THREAD

**Issue by Exeteres** [nonara/ts-patch#16]
It seems that ts-node uses another way to show errors, so ts-patch methods for altering diagnostics don't work.
Any ideas? Maybe it's time to apply some patches to ts-node? 🤔

**Comment by nonara** [comment]
Thanks for the report! That's an interesting angle I hadn't considered.

Altering diagnostics was built to work for TSC, which uses `emitFilesAndReportErrors`. It won't work if you're creating a `Program` instance, but in that case you wouldn't need it, as you could directly modify.

Patching ts-node would not be a desirable route, but I have an idea in mind that would likely work. I would need to dig into `ts-node` a bit.

I'm a bit backlogged right now, so it may be a bit before I can look into it.

**Comment by nonara** [comment]
I took a look into it. Turns out `ts-node` uses `LanguageService` to emit its files and get diagnostics. I believe the relevant portion of code is here: https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L571-L595

You can see that it creates errors based on the diagnostics that it gets.

With that in mind, this actually falls under the category of LanguageService. This means you should be able to make a LS plugin which replicates the removal of diagnostics behaviour in the same way you would for IDE.

That said, depending on your use-case, `ts-node` also has an option to ignore certain diagnostics by error code. Check out the `--ignore-diagnostics` flag. That may be sufficient for you!

I'm going to go ahead and close the issue, because it's `LanguageService` related, but feel free to still discuss if you have questions.

**Comment by Exeteres** [comment]
Thanks for the investigation!
I don't know how, but I missed the `--ignore-diagnostics` flag that works perfect.
Regarding to LS plugins, I think that ts-node doesn't load them. I have one that filters diagnostics and works fine in VSCode, but don't work in ts-node. However, using `--ignore-diagnostics` flag is enough.

**Comment by nonara** [comment]
No problem! Glad you got it working!

BTW, if your code to filter diagnostics in the LS is on github, I'd be happy to link it as an example.

**Comment by Exeteres** [comment]
That [LS plugin](https://github.com/Exeteres/function-decorator-ts-plugin/blob/05f47e550884035c040a10f8b4fd3e72832a1c4c/src/plugin/index.ts#L13) is part of my attempt to implement function decorators.
It works fine, but doesn't typecheck decorator expressions.

BTW, the transformer didn't work as I expected.
[I had to use the program replace feature](https://github.com/Exeteres/function-decorator-ts-plugin/blob/05f47e550884035c040a10f8b4fd3e72832a1c4c/src/transformer/index.ts#L72), otherwise typescript doesn't create `require()` calls for imported stuff in decorator expressions (eg [imported decorators](https://github.com/Exeteres/function-decorator-ts-plugin/blob/05f47e550884035c040a10f8b4fd3e72832a1c4c/example/src/index.ts#L1)).
So it can be called an experiment rather than something that can be actually used.
And altering diagnostics feature in this case is no longer needed :D
