### ISSUE TITLE
Can't run tsc -p <another_dir>/tsconfig.json

### ISSUE THREAD

**Issue by nonara** [nonara/ts-patch#50]
Presently, `ts-patch` resolves the plugins relative to `cwd`. This means that plugins cannot be resolved if executing from a directory outside of where the `tsconfig.json` file is stored.

This behaviour is not ideal, however, because v2 is already marked out for [the rewrite](https://github.com/nonara/ts-patch/tree/v2), I will be adding a command to the cli that allows changing the resolution strategy.

I will post the how-to, when it is ready.

**Comment by craigphicks** [comment]
So this new command line option is necessary to accommodate existing transforms which may depend upon `process.cwd()` rather than `process.getCompilerOptions().configFilePath`?

But those transforms are currently, due to the bug, only being called when `tsc` is executed from the directory where `tsconfig.json` is stored.  So if the current execution directory is included in existing usage, then the change will not cause any existing usage to break.  Therefore the change is suitable for a minor version update.  Probably.

**Comment by nonara** [comment]
Already fixed

**Comment by nonara** [comment]
Looking over the code further, I did actually already fix this. I just didn't see the projectDir overwrite for tsc.

See comments in other thread for more detials.
