### ISSUE TITLE
[Feature] Support transformers written as ES modules

### ISSUE THREAD

**Issue by aomarks** [nonara/ts-patch#58]
It is not currently possible to import a transformer that is written a standard ES module. Only transformers written as CommonJS modules work currently.

Node has supported standard ES modules since v12, so that's all currently supported versions of Node: https://nodejs.org/en/about/releases/. Node packages are increasingly being published as ES modules instead of CommonJS, so it would be great to be able to use them here too! One huge advantage of ES modules is that they can run directly both in Node and browsers.

https://nodejs.org/api/esm.html#esm_introduction

Note this doesn't require writing `ts-patch` itself in ES modules, since there is bi-directional interoperability in Node. ​To import an ES module from a CommonJS module, use `const mod = await import("./some-module.js")` instead of `require`. To check if a module *should* be imported as an ES module, look in its `package.json` for the `{"type": "module"}` field.

I see a new version is being written at https://github.com/nonara/ts-patch/discussions/40 -- I think this would be an awesome thing to include in the rewrite.

Thanks!

**Comment by nonara** [comment]
Thanks for the report. ESModule support is definitely important. I'm not sure if I'm missing something, but I'm not sure how you could implement this into CJS code without dramatic rewrites.

For example, the typescript compiler is a synchronous cjs file. In the case of `tsc.js`, you could probably make it work because you can pre-resolve the transformer files early (as you know exactly what tsconfig you're working with at execution, and you're only doing one). Even still, you'd still have to wrap the actual executable portion and only call it after you've resolved the promise for resolution.

In the case of the API (ie. `typescript.js`), it becomes much more difficult. You'd need to convert `createProgram` to an async function, and thus modify everything that leads to it, and the whole chain that use those, etc. Am I misunderstanding something? Is there a way to synchronously import via expression?

**Comment by aomarks** [comment]
Ah, interesting. It didn't occur to me that because you are *patching* TypeScript, it is not easy for you to add arbitrary asynchronous setup work. It is true that there is no synchronous dynamic import for ES modules.

I'm coming over from `ttypescript` (since it seems a bit abandoned). I'm guessing it would be easier to do this in the model it uses, because it's an alternate frontend entirely rather than a patcher -- so presumably it could just do arbitrary work before invoking any TypeScript APIs (in this case waiting for all the modules specified in `compilerOptions.plugins.transform` to be imported).

**Comment by nonara** [comment]
We're essentially doing the same thing as `ttypescript`, with the main differences being that we add a few more features and ours is done once, where tts does it each time it's loaded.

Both libraries patch `ts.createProgram`, which gets called from many places throughout the compiler. If we made that an async function, it would affect everything that calls it.

Actually just supporting `tsc` would be relatively simple. As you mentioned, it could do the resolution work before executing the compilation. It's easy for us to add that in. The issue is that we also support the TypeScript compiler API, which can be called multiple times, with different configs. But as I mentioned, the real issue is that the typescript library (which natively handles transformers) doesn't support esm transformers.

All of this has mostly been my thinking the problem through out loud, though. Not necessarily relevant to the ask! 😄 I think the answer is just in adding support further upstream, as we did for supporting `.ts` transformers.

Have you tried using `--loader ts-node/esm` as a node parameter (or in `NODE_OPTIONS` env)?

**Comment by ClearedFram3** [comment]
Does TS 5.0 being mostly ESM now change this at all?

**Comment by nonara** [comment]
This is now supported. You can try the current release candidate if you'd like to check it out early. 

Just use `yarn add -D ts-patch@3.0.0-rc2`

Let me know if it works for you!

**Comment by samchon** [comment]
@nonara Not working.

There had not been any problem in `ts-patch@2.1.0`.

## TypeScript v4.9
```bash
$ npx ts-patch install
[!] Some files can't be patched! You can run again with --verbose to get specific error detail. The following files are unable to be patched:
  - D:\github\samchon\typia@master\node_modules\typescript\lib\tsc.js
  - D:\github\samchon\typia@master\node_modules\typescript\lib\typescript.js

$ npx ts-patch install --verbose
[~] Patching tsc.js in D:\github\samchon\typia@master\node_modules\typescript\lib
[~] Writing backup cache to D:\github\samchon\typia@master\node_modules\.cache\ts-patch\da30b49ec053846f15152e30247a54ab\tsc.js
[!] Cannot patch TS version <5
[~] Patching typescript.js in D:\github\samchon\typia@master\node_modules\typescript\lib
[~] Writing backup cache to D:\github\samchon\typia@master\node_modules\.cache\ts-patch\84f1848a4a4eba19e6d8c1694d4ff746\typescript.js
[~] Writing backup cache to D:\github\samchon\typia@master\node_modules\.cache\ts-patch\84f1848a4a4eba19e6d8c1694d4ff746\typescript.d.ts
[!] Cannot patch TS version <5
[!] Some files can't be patched! You can run again with --verbose to get specific error detail. The following files are unable to be patched:
  - D:\github\samchon\typia@master\node_modules\typescript\lib\tsc.js
  - D:\github\samchon\typia@master\node_modules\typescript\lib\typescript.js
```

## TypeScript v5.0
```
Error: Cannot find module './transformers/FileTransformer'
Require stack:
- D:\github\samchon\typia@master\src\transform.ts
- D:\github\samchon\typia@master\node_modules\typescript\lib\tsc.js
- D:\github\samchon\typia@master\node_modules\typescript\bin\tsc
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Module.require (D:\github\samchon\typia@master\node_modules\typescript\lib\tsc.js:353:45)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (D:\github\samchon\typia@master\src\transform.ts:8:27)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Module.requireCjs (D:\github\samchon\typia@master\node_modules\typescript\lib\tsc.js:375:35)
    at Module.require (D:\github\samchon\typia@master\node_modules\typescript\lib\tsc.js:361:75)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.resolveFactory (D:\github\samchon\typia@master\node_modules\typescript\lib\tsc.js:310:38)
    at PluginCreator.createTransformers (D:\github\samchon\typia@master\node_modules\typescript\lib\tsc.js:170:41) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\github\\samchon\\typia@master\\src\\transform.ts',
    'D:\\github\\samchon\\typia@master\\node_modules\\typescript\\lib\\tsc.js',
    'D:\\github\\samchon\\typia@master\\node_modules\\typescript\\bin\\tsc'
  ]
}
```

**Comment by Mexican-Man** [comment]
I'm on v3.0.2, and I'm unable to get ESM working. 
```
plugins: "..." does not have an export "default": {}`.
```
It seems when [`loadPlugin` is called](https://github.com/nonara/ts-patch/blob/85022cab5939b8dcdb1d9dda0e312ecf0e30fc7d/projects/patch/src/plugin/resolve-factory.ts#L62C3), it tries to `require(transformerPath)`. However, `require` does not support ESM as far as I know. It's also worth noting that `transformerPath` is `""` anyway, so `require` returns `{}`. `transformerPath` is empty because [it's assigned using `require.resolve`](https://github.com/nonara/ts-patch/blob/85022cab5939b8dcdb1d9dda0e312ecf0e30fc7d/projects/patch/src/plugin/resolve-factory.ts#L26).

Unless I'm totally mistaken here, using `import` instead of `require` would fix the issue. However, that would require the use of async/await. I'm not sure about `require.resolve`, though, because using `import.meta.resolve` can only be called inside of a module, itself.

**Comment by nonara** [comment]
@Mexican-Man Can you make a repro?

Esm requires the esm package, but it should warn you of that. The plugin path should be relative file path to the plugin file.

**Comment by Mexican-Man** [comment]
@nonara It's more than likely I'm messing something up. Here's a [reproduction with instructions](https://github.com/Mexican-Man/ts-patch-repro). Please let me know if you spot anything.

**Comment by zero1zero** [comment]
did you ever get to the bottom of this? I'm using ESM and continue to get:
>evalmachine.<anonymous>:385
                        throw new tsp.TsPatchError(`tsconfig.json > plugins: "${configTransformValue}" does not have an export "${importKey}": ` +
                        ^
TsPatchError: tsconfig.json > plugins: "test" does not have an export "default": {}


Not sure how to get around it or where the issue is

**Comment by zero1zero** [comment]
Opened a new issue here: https://github.com/nonara/ts-patch/issues/172
