### ISSUE TITLE
Correct ts-patch installation in monorepo

### ISSUE THREAD

**Issue by KillWolfVlad** [nonara/ts-patch#70]
Hi! We have a monorepo build upon on yarn 3 with `node-modules` linker (you can explorer it here https://github.com/Byndyusoft/nest-template, if you want). In each `package.json` (except root `package.json` with workspaces) we have:
- `ts-patch`: 2.0.1
- `typescript`: 4.5.2
- `postinstall` script to install ts-patch: `(ts-patch install) || true` (we need `|| true` part to prevent `yarn workspaces focus --all --production` to fail when `ts-patch` will not be found)

yarn 2/3 run `postinstall` in parallel (see [here](https://github.com/yarnpkg/berry/issues/648)), so different launches of ts-patch will be concurrent for modify same files (you can view incorrect patch [here](https://github.com/Byndyusoft/nest-template/runs/4396943863?check_suite_focus=true#step:5:5)). I think it is heisenbug and hard to reproduce, re run job can resolve fail build.

I think the best way to solve this issue is use a lock files (as in Linux package managers e.g. `apt` or `pacman`) or any other mutex to prevent multiple launches for same typescript package.

Maybe we should install ts-patch differently and this installation way should be added to documentation.

@nonara what do you think?

Thanks for any help!

**Comment by KillWolfVlad** [comment]
If you don't have permission to view our logs with incorrect patch, I attach screenshot here:
![image](https://user-images.githubusercontent.com/18448635/144480909-48afacea-a2e9-4653-95ca-3503aaf17316.png)

**Comment by nonara** [comment]
Hello! Interesting scenario. Being a shared development dependency which installs to the project root, I would advise adding it to the workspace's `devDependencies`. Also, are you not able to use `prepare` with yarn3?

> script to install ts-patch: (ts-patch install) || true (we need || true part to prevent yarn workspaces focus --all --production to fail when ts-patch will not be found)

If it suits your use-case, you can use `npx ts-patch ...`. This is what I do if I'm not certain a dev dep has been installed yet. This causes it to prefer the dev dep or execute from temp install if not.

> I think the best way to solve this issue is use a lock files (as in Linux package managers e.g. apt or pacman) or any other mutex to prevent multiple launches for same typescript package.

It's an interesting problem. Realistically, I don't think adding mutex makes sense within the core application, mainly because the reasonable expectation is that the user would not try to run it multiple times pointing to the same target. If a user needed to accomplish something like that for some reason, it would make more sense to write a launch script.

It is possible that yarn gives an environment variable with a run id or something similar. If that was the case, you could make a simple script which checked a file to see if the id matches. If not, write to the file  and proceed. If so, noop.

That said, I think the better solution is going to be to try to only run it once. The reason we use `prepare` is because this will run whenever dependencies are installed / updated. That said, I don't know if yarn3 functionality is different. If it turns out that there is no good option with yarn3, then maybe adding the functionality to the core application would make sense.

I'll be interested to hear what you find out.

**Comment by nonara** [comment]
Thinking about it a little further, I'm not sure this should be happening. I would think that `writeFileSync` would lock. It's hard to imagine they'd collide somehow.

One solution might be to implement https://github.com/moxystudio/node-proper-lockfile - If you're interested in doing a PR, I think it would be reasonable to implement that.

**Comment by KillWolfVlad** [comment]
> Also, are you not able to use `prepare` with yarn3?

Yarn3 doesn't support `prepare` script (see [here](https://github.com/yarnpkg/berry/issues/2305)). So, I think `postinstall` script is the best way to auto install ts-patch for Yarn3.

> If it suits your use-case, you can use `npx ts-patch ...`

I don't understand your idea, can you explain in more detail or send me a link to the examples repository?

> I think the better solution is going to be to try to only run it once

Agree. I moved ts-patch install to root `package.json` (you can check [PR](https://github.com/Byndyusoft/nest-template/pull/41), if you want). Thank you for your quick and high-quality response.

**Comment by nonara** [comment]
> Yarn3 doesn't support prepare script

Ah, ok. Thanks. I remember someone else mentioning something along those lines. Looking forward to familiarizing myself more with y3 when I can finish the rewrite.

> I don't understand your idea

Not sure if it will fit your situation, but I've taken to using `npx <cli>` whenever I am not sure that a package will be there (ie. if yarn install hasn't happened yet or I might have wiped the node_modules)

Essentially, it guarantees that something runs, whether or not it's been locally installed. It prefers the local install, when it exists, otherwise it installs to a temp location for a one-shot run. That may not be what you're looking for, though. I don't know what your build / pipeline process does. But thought I'd share in case it helps.

> Agree. I moved ts-patch install to root package.json (you can check PR, if you want). Thank you for your quick and high-quality response.

Excellent! You're very welcome. Glad you got it working.

**Comment by pkerschbaum** [comment]
In case anyone helps this:

I am working in a monorepo using Yarn v1 and I also had the problem that sometimes, after `yarn install`, it seemed that `tsc` was broken in some of the workspaces. Removing `node_modules` and installing again would then sometimes solve the issue, but not always.

I think this was because of parallel invocations of `ts-patch`, but not because I ran it with `lerna run --parallel` or something.  
It seems like the parallel invocations of `ts-patch` boiled down to the fact that some of my workspaces depend on each other (as it is often the case in monorepos). `yarn install` would then run multiple times in those "workspace dependencies" because npm scripts like `postinstall` or similar run *every time the workspace is "installed" as a dependency for another workspace*.  
And by chance this would happen at the same time (since Yarn v1 does install packages in parallel to speed up things).

My workaround, which is sufficient for my monorepo project:
* Avoid running `ts-patch` in any NPM script of the workspace `package.json`'s
* And instead, I added this `postinstall` script in the root `package.json`:
    ```json
    "postinstall": "lerna exec --parallel \"yarn ts-patch install -s\""
    ```

I have this workaround in place for a couple of days and not a single time I had a broken `tsc` anymore.  
In my case, every workspace is a TypeScript project, but if not one could adapt that `lerna exec` command so that it does not break if it fails in any of the workspaces.
