### ISSUE TITLE
How to chain transformers?

### ISSUE THREAD

**Issue by AlCalzone** [nonara/ts-patch#73]
I'm currently trying to implement a specialized version of `typescript-is/lib/transform-inline/transformer` for a project. To do so, I want to apply a custom transformer which generates code that should then be transformed by `typescript-is`. E.g.

Input:
```ts
import { validateArgs } from "@zwave-js/maintenance";

type Foo = {
	bar: number;
} & (
	| { baz: string; }
	| { bap: boolean; }
);

class CFoo {
	@validateArgs()
	test(arg1: number, arg2: string, arg3: Foo) {
		// ... implementation
	}
}

new CFoo().test(1, "2", {
	bar: 4,
	baz: "foo",
});
```

Output of my transformer, should be input to `typescript-is`:
```ts
import { is, createIs } from "typescript-is";

const isFoo = createIs<Foo>();

type Foo = {
	bar: number;
} & (
	| { baz: string; }
	| { bap: boolean; }
);

class CFoo {
	test(arg1: number, arg2: string, arg3: Foo) {
		if (!is<number>(arg1)) {
			throw new ZWaveError(
				"arg1 is not a number",
				ZWaveErrorCodes.Argument_Invalid,
			);
		}
		if (!is<string>(arg2)) {
			throw new ZWaveError(
				"arg2 is not a string",
				ZWaveErrorCodes.Argument_Invalid,
			);
		}
		if (!isFoo(arg3)) {
			throw new ZWaveError(
				"arg3 is not a Foo",
				ZWaveErrorCodes.Argument_Invalid,
			);
		}

		// ... implementation
	}
}

new CFoo().test(1, "2", {
	bar: 4,
	baz: "foo",
});
```

From this code, `typescript-is` should generate the actual output. However it seems that both my transformer and the `typescript-is` transformer see the identical input source code. Not sure if this is intended or if there is a better way to do what I plan to do?

**Comment by nonara** [comment]
Sounds like your situation is related to the fact that the TypeScript compiler does not recompute types between each transformation.

I'm assuming you have it set so that the plugins order is 1) your plugin 2) typescript-is plugin

During transformation, all transformers are loaded in a chain. Each source file passes the the AST through the chain. 

This is okay if you're just doing transformation of AST nodes, but if you're using the typechecker API at all, you can't get information from newly created or modified nodes. So in this case, typescript-is most likely cannot determine what `Foo` points to, because as far as it understands, this is just an identifier without any understood reference link within the typechecker.

Why does that happen? Because the "type walker" process only happens once on the original source.

## Solutions

For your case, you have a couple of options.

One is to fork typescript-is and add your logic. While this would be easy, it may not be ideal for your situation.

Next, you can open up the typescript-is logic and see if there is an API you can use during your transformer. Probably not the best solution.

Finally, there is a solution that I built into ts-patch to be able to handle this very issue, as it comes up frequently, where we need to rebuild the `Program` (effectively update the type information after initial transformation) before other transformers occur.

This is what I call a `Program` transformer. You can see a simple example here:

https://github.com/nonara/ts-patch/discussions/29

This can easily be used as a template, where you can swap out the transformer logic for your @validateArgs transformer.

## Explanation

Simply add your program transformer in plugins along with typescript-is and it should work.

What it's doing is performing your transform during `Program` creation, then it re-creates the `Program` with your new code before it passes on to the next transformers.

If you have any questions, feel free to let me know, and good luck with it!

**Comment by AlCalzone** [comment]
Thanks for the detailed answer. I ended up building my own transformer based on `typescript-is` which is tailored better to my use case. However, I can foresee the program transformer being useful down the road, as I have some fully or partially auto-generated files, which are currently a separate build step.
